public class op_trigger_class{
    public static void op_amount_check(List<Opportunity> ops){
                Double total_amount=0;
                
                for(Opportunity o1 : [select Amount from Opportunity where createdByID = :UserInfo.getUserID() AND createdDate= TODAY])
                 {
                    total_amount +=o1.Amount;
                 }
                 
                 for(Opportunity o2: ops){
                 total_amount +=o2.Amount;
                 if(total_amount>500000)
                 o2.addError('you have exceeded the daily limit');
                 }
                                 
    
    }

}